### ISSUE TITLE
Archive this repository

### ISSUE THREAD

**Issue by Steve0Greatness** [JaydenDev/MyScratchPagem#5]
It seems this repository is not being actively worked on anymore, it would be a good idea to archive it.

## path to archive
`Settings` > `Danger Zone` > `Archive this repository`

**Comment by JaydenDev** [comment]
> It seems this repository is not being actively worked on anymore, it would be a good idea to archive it.
> ## path to archive
> 
> `Settings` > `Danger Zone` > `Archive this repository`

I archive repositories often, so I know where it is :)
